image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  # Overrides the image tag whose default is {{ .Chart.AppVersion }}
  # Set to "-" to not use the default value
  tag: 2.1.10-debug
  digest:
  pullPolicy: Always

openShift:
  enabled: true
  securityContextConstraints:
    # Create SCC for Fluent-bit and allow use it
    create: false
    name: ""
    annotations: {}
    # Use existing SCC in cluster, rather then create new one
    existingName: "logging"

securityContext:
    privileged: true

extraVolumes: 
  - name: es-ca-vol
    secret: 
      secretName: elasticsearch-external

extraVolumeMounts: 
  - name: es-ca-vol
    readOnly: true
    mountPath: "/fluent-bit/etc/certs"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: env
          operator: In
          values:
          - HML
env: 
  - name: TZ
    value: "America/Recife"
  - name: ELASTIC_USER
    valueFrom:
      secretKeyRef:
        name: elastic-creds
        key: username
  - name: ELASTIC_PASS
    valueFrom:
      secretKeyRef:
        name: elastic-creds
        key: password       
  - name: ELASTIC_HOST
    valueFrom:
      secretKeyRef:
        name: elastic-creds
        key: host   
  - name: ELASTIC_PORT
    valueFrom:
      secretKeyRef:
        name: elastic-creds
        key: port                    

luaScripts:
  remove_dummy.lua: |
    function remove_dummy(tag, timestamp, record)
        new_log=string.gsub(record["message"],"%d+-%d+-%d+T%d+:%d+:%d+.%d+Z%sstdout%sF%s","")
        new_record=record
        new_record["message"]=new_log
        return 2, timestamp, new_record
    end  

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        # Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*_homologacao_*.log, /var/log/containers/*_pos-homologacao_*.log
        Parser json
        Tag kube.*
        Read_from_head true
        Multiline On
        Parser_Firstline multiline
        Mem_Buf_Limit 50MB
        Skip_Long_Lines Off
        Skip_Empty_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/*_homologacao_*.log, /var/log/containers/*_pos-homologacao_*.log
        Parser json
        Tag kube.*
        Read_from_head true
        Multiline On
        Parser_Firstline multiline
        Mem_Buf_Limit 50MB
        Skip_Long_Lines Off
        Skip_Empty_Lines On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Buffer_Size 256KB
        Merge_Log On
        Merge_Log_Trim On
        Labels On
        Annotations On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    # [FILTER]
    #     Name           lua
    #     Match          kube.*
    #     call remove_dummy
    #     Script /fluent-bit/scripts/remove_dummy.lua        

    # [FILTER]
    #     Name  modify
    #     Match kube.*
    #     Rename  message log

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host ${ELASTIC_HOST}
        Port  ${ELASTIC_PORT}
        Retry_Limit False
        HTTP_User       ${ELASTIC_USER}
        HTTP_Passwd     ${ELASTIC_PASS}
        Logstash_Format On
        Logstash_Prefix logs
        # Logstash_Prefix_Key $kubernetes['namespace_name']
        Trace_Error       Off
        Trace_Output      Off       
        Suppress_Type_Name On     
        tls On
        tls.verify Off
        tls.ca_file /fluent-bit/etc/certs/http_ca.crt

  # [OUTPUT]
  #     Name es
  #     Match host.*
  #     Host 10.100.6.111
  #     Port  9200
  #     Logstash_Format On
  #     Logstash_Prefix node
  #     Retry_Limit False
  #     HTTP_User       ${ELASTIC_USER}
  #     HTTP_Passwd     ${ELASTIC_PASS}
  #     Suppress_Type_Name On
  #     tls On
  #     tls.verify Off
  #     tls.ca_file /fluent-bit/etc/certs/http_ca.crt
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
  ## This configuration is deprecated, please use `extraFiles` instead.
  upstream: {}

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    # CRI Parser
    [PARSER]
        Name        cri-custom
        Format      regex
        Regex       ^(?<time>[^ ]+)\s*(?<stream>stdout|stderr)\s*(?<logtag>[^ ]*)\s*(?<timestamp>\d{2}:\d{2}:\d{2},\d{3})\s*(?<level>INFO|ERROR|WARN|WARNING|TRACE|DEBUG|FATAL|SEVERE)\s*\[(?<class>[^\]]+)]\s*(?<thread>\(.*\))\s+(?<message>.*?)(?=\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}|\Z)$  
        #Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name multiline
        Format regex
        Regex /(?<timestamp>\d{2}:\d{2}:\d{2},\d{3})\s*(?<level>INFO|ERROR|WARN|WARNING|TRACE|DEBUG|FATAL|SEVERE)\s*\[(?<class>[^\]]+)]\s*(?<thread>\(.*\))\s+(?<message>.*?)(?=\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}|\Z)/
        Time_Key  time
        Time_Format %b %d %H:%M:%S

      [PARSER]
        Name binarios_multiline
        Format regex
        Regex /(?<date>\d{4}-\d{2}-\d{2})\s*\s*(?<timestamp>\d{2}:\d{2}:\d{2}\.\d{3})\s*(?<level>INFO|ERROR|WARN|WARNING|TRACE|DEBUG|FATAL|SEVERE)\s*.?\s*---\s*\[(?<thread>[^\]]+)]\s*(?<class>.*:)\s*(?<message>.*)/
        Time_Key  time
        Time_Format %b %d %H:%M:%S
